[package]
name = "yvytuatã"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
noise = "0.9.0"
rand = "0.7.3"
pprof = { version = "0.13", features = ["flamegraph"] }

[profile.release]
#opt-level = 3
#debug = false
#lto = true
#panic = "abort"
